name: flutter_fgbg
description: Flutter plugin to detect when app(not Flutter container) goes to background or foreground
version: 0.6.0
homepage: https://github.com/ajinasokan/flutter_fgbg

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# declare support for all of the following platforms, even though some of them
# don't require any special setup or native code to work
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:
  plugin:
    platforms:
      android:
        package: com.ajinasokan.flutter_fgbg
        pluginClass: FlutterFGBGPlugin
      ios:
        pluginClass: FlutterFGBGPlugin
