name: flutter_fgbg
description: Flutter plugin to detect when app(not Flutter container) goes to background or foreground
version: 0.8.0
homepage: https://github.com/ajinasokan/flutter_fgbg

environment:
  sdk: ^3.8.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ajinasokan.flutter_fgbg
        pluginClass: FlutterFGBGPlugin
      ios:
        pluginClass: FlutterFGBGPlugin
